### ISSUE TITLE
Lost Litcoin transfered in. No show in browser transaction address section....Sept 12_21

### ISSUE THREAD

**Issue by Tooniecoin** [atomex-me/atomex.client.wpf#15]
Sent to Atomex Sept 12/21
LP63ioktmZY5QtzLngNneSdkAdrMXZLjU3

https://litecoinblockexplorer.net/tx/c75f4ed76adb242f5b4fca1b58f632f7706d964c5f5caf3a37780c57a190e784
LP63ioktmZY5QtzLngNneSdkAdrMXZLjU3
https://explorer.viawallet.com/ltc/address/LP63ioktmZY5QtzLngNneSdkAdrMXZLjU3

**Comment by Tooniecoin** [comment]
3929abfc21371ce87f8f79614d7701d1febbdb3993a5d674dfb14277ab521f0c
Received this one (above) on Sept. 12 but not the other ..... jU3 one.

**Comment by matsakiv** [comment]
I apologize for the long answer! Most likely the problem was related to the data provider for Litecoin. We changed the data provider, so the problem is probably no longer relevant
