### ISSUE TITLE
wrong description of repository

### ISSUE THREAD

**Issue by Kwaskoff** [atomex-me/atomex.client.wpf#2]
Change please "for OS Windows" to "any OS", because I find here MacOS and Ubuntu binaries =)
![image](https://user-images.githubusercontent.com/15308024/94277312-1270b980-ff52-11ea-9988-b8b2902bfd7d.png)

**Comment by nmm5055** [comment]
0xa3b1F39783CA826197222687C70A7CBdD8526ae8

**Comment by matsakiv** [comment]
WPF project is no longer supported. Now the new version of the application uses a cross-platform solution on Avalonia UI: [atomex.client.desktop](https://github.com/atomex-me/atomex.client.desktop)
